import {
  Ionicons,
  MaterialIcons,
  Entypo,
  FontAwesome,
  AntDesign,
  FontAwesome5,
  MaterialCommunityIcons,
} from "@expo/vector-icons";
export const data = {
  BottomMenuData: [
    {
      id: 1,
      Icon: Ionicons,
      IconName: "home-sharp",
      iconName2: "home-outline",
      screen: "Home",
    },
    {
      id: 2,
      Icon: MaterialIcons,
      IconName: "home-sharp",
      screen: "Assignment",
    },
    {
      id: 3,
      Icon: Entypo,
      IconName: "home-sharp",
      screen: "HomeWork",
    },
    {
      id: 4,
      Icon: FontAwesome,
      IconName: "home-sharp",
      screen: "Pay Fee",
    },
  ],
  Assignment: [
    {
      id: 1,
      Icon: FontAwesome5,
      name: "react",
      title: "Theoretical Physics",
      dec: "the branch of physics that deals with developing ",
      updates: 6,
      color: "#2de874",
      bgColor: "#2de87432",
    },
    {
      id: 2,
      Icon: MaterialCommunityIcons,
      name: "chemical-weapon",
      title: "Mathematics HomeTask",
      dec: "Fun maths games and activities for kids. ",
      updates: 7,
      color: "#6f04c7",
      bgColor: "#6f04c732",
    },
    {
      id: 3,
      Icon: FontAwesome5,
      name: "dumbbell",
      title: "Physical Exercise",
      dec: "movements and activities done to keep your body ",
      updates: 5,
      color: "#de04cb",
      bgColor: "#de04cb32",
    },
    {
      id: 4,
      Icon: FontAwesome5,
      name: "react",
      title: "Theoretical Physics",
      dec: "the branch of physics that deals with developing ",
      updates: 5,
      color: "#6f54c7",
      bgColor: "#6f54c732",
    },
    {
      id: 5,
      Icon: MaterialCommunityIcons,
      name: "chemical-weapon",
      title: "Mathematics HomeTask",
      dec: "Fun maths games and activities for kids. ",
      updates: 6,
      color: "#2ac874",
      bgColor: "#2dd87432",
    },
    {
      id: 6,
      Icon: FontAwesome5,
      name: "dumbbell",
      title: "Physical Exercise",
      dec: "movements and activities done to keep your body ",
      updates: 7,
      color: "#dea4cb",
      bgColor: "#dea4cb32",
    },
  ],
  SchoolUpdate: [
    {
      id: 1,
      Icon: FontAwesome,
      name: "newspaper-o",
      title: "News",
      updates: 6,
      color: "#2de874",
      bgColor: "#2de87432",
    },
    {
      id: 2,
      Icon: AntDesign,
      name: "calendar",
      title: "Events",
      updates: 7,
      color: "#de04cb",
      bgColor: "#de04cb32",
    },
    {
      id: 3,
      Icon: Entypo,
      name: "sound",
      title: "Leave",
      updates: 5,
      color: "#6f04c7",
      bgColor: "#6f04c732",
    },
    {
      id: 4,
      Icon: Entypo,
      name: "sound",
      title: "Leave",
      updates: 5,
      color: "#6f54c7",
      bgColor: "#6f54c732",
    },
    {
      id: 5,
      Icon: FontAwesome,
      name: "newspaper-o",
      title: "News",
      updates: 6,
      color: "#2ac874",
      bgColor: "#2dd87432",
    },
    {
      id: 6,
      Icon: AntDesign,
      name: "calendar",
      title: "Events",
      updates: 7,
      color: "#dea4cb",
      bgColor: "#dea4cb32",
    },
  ],
};
